#pragma once

#define DATA_WALL 1
#define DATA_DIRT 2
#define DATA_STEELWALL 3
//zamienia kamienie w klejnoty
#define DATA_MAGICWALL 4
#define DATA_MAGICWALL_ACTIVE 5
//firefly - eksplozja
#define DATA_FIREFLY_RIGHT 6
#define DATA_FIREFLY_LEFT 7
#define DATA_FIREFLY_TOP 8
#define DATA_FIREFLY_DOWN 9
//idk
#define DATA_BUTTERFLY_RIGHT 10
#define DATA_BUTTERFLY_LEFT 11
#define DATA_BUTTERFLY_UP 12
#define DATA_BUTTERFLY_DOWN 13

#define DATA_BOULDER 14
#define DATA_BOULDER_FALL 15
#define DATA_DIAMOND 16
#define DATA_DIAMOND_FALL 17
#define DATA_SPACE 18
#define DATA_SLIME 19
#define DATA_INBOX 20
#define DATA_OUTBOX 21
#define DATA_OUTBOX_ACTIVE 22
#define DATA_AMOEBA 23
#define DATA_ROCKFORD 24
#define DATA_ROCKFORD_GRAB 25
//eksplozja zajmuje sporo klatek
#define DATA_EXPLOSION1 26
#define DATA_EXPLOSION2 27
#define DATA_EXPLOSION3 28
#define DATA_EXPLOSION4 29
#define DATA_EXPLOSION5 30
#define DATA_DEXPLOSION1 31
#define DATA_DEXPLOSION2 32
#define DATA_DEXPLOSION3 33
#define DATA_DEXPLOSION4 34
#define DATA_DEXPLOSION5 35
#define DATA_DRAW_LINE 36
#define DATA_DRAW_POINT 37
#define DATA_DRAW_FILLRECT 38
#define DATA_DRAW_FILLRECT2 39
#define DATA_DRAW_RASTER 40
#define DATA_DRAW_RECTANGLE 41
#define DATA_COLOR_ORANGE 42
#define DATA_COLOR_GRAY1 43
#define DATA_COLOR_GRAY2 44
#define DATA_COLOR_WHITE 45
#define DATA_COLOR_PURPLE 46
#define DATA_COLOR_BROWN 47
#define DATA_COLOR_LIGHTBLUE 48
#define DATA_COLOR_LIGHTRED 49
#define DATA_COLOR_RED 50
#define DATA_COLOR_GREEN 51
#define DATA_COLOR_BLUE 52
